post http://localhost:5000/api/signup
Content-Type: application/json

{
    "username":"Anand",
    "email":"b191832@gmail.com",
    "password":"123"
}
###
post http://localhost:5000/api/login
Content-Type: application/json

{
    "email":"anandkumarch337@gmail.com",
    "password":"12"
}
###
get http://localhost:5000/api/allsubtask/67a5f129fd587cb2c618977d
Content-Type: application/json

### 
get http://localhost:5000/api/particulartask
Content-Type: application/json
x-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTI0Y2UwNDdmMzFmNjkwNjU0Mjg5MSIsImlhdCI6MTczODkyNDU4MCwiZXhwIjoxNzM4OTI4MTgwfQ.U9v9PYDVFjws6v4t1dEJLhQREOFcvgL40o5ZvtCTOoY

###
delete http://localhost:5000/api/deletesubtask
Content-Type: application/json

{
    "_id":"67a6147d9f9c9040ba8d71db"
}